### ISSUE TITLE
video scrubbing

### ISSUE THREAD

**Issue by YLPeng** [JadynAi/MediaLearn#3]
你好 读了你的一篇文章感觉写的不错。 kotlin code 也写的很干净

最近需要在android 上面实现 video scrubbing的功能， 就是用户可以通过时间轴来实时定位视频帧 （跟iphone的 视频编辑时浏览的功能差不多）。现在大多数的video seek 都是拉到一个时间点 然后视频图像才更新。
不知道你有没有什么想法或者好方法来实现这个功能？

多谢～

**Comment by JadynAi** [comment]
> 你好 读了你的一篇文章感觉写的不错。 kotlin code 也写的很干净
> 
> 最近需要在android 上面实现 video scrubbing的功能， 就是用户可以通过时间轴来实时定位视频帧 （跟iphone的 视频编辑时浏览的功能差不多）。现在大多数的video seek 都是拉到一个时间点 然后视频图像才更新。
> 不知道你有没有什么想法或者好方法来实现这个功能？
> 
> 多谢～

代码全都在这个项目了哦~
